name: Publish

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches:
      - main
    tags:
      - v*

jobs:
  publish:
    name: Publish to PyPI
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          path: artifacts

      - name: Prepare distribution files
        run: |
          mkdir -p dist
          find artifacts -type f \( -name "*.whl" -o -name "*.tar.gz" \) -exec mv {} dist/ \;
          ls -l dist/

      - name: Check if prerelease
        id: check_prerelease
        run: |
          if [[ ${{ github.ref }} =~ .*-alpha|beta|rc.* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      - name: Publish to PyPI
        if: steps.check_prerelease.outputs.is_prerelease == 'false'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}